on:
  push:
    branches:
      - dev
name: Deploy website
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.8
        with:
          sftp: false
          host: eg77.mirohost.net
          username: metrouiS
          password: ${{ secrets.FTP_PASSWORD }}
          remote_folder: dev.metroui.org.ua/
          local_folder: ./dist/
          cleanup: false
          passive: true
          