on:
  push:
    branches:
      - dev
name: Deploy website
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push files
        uses: sand4rt/ftp-deployer@v1.8
        with:
          host: eg77.mirohost.net
          port: 21
          username: metrouiS
          password: ${{ secrets.FTP_PASSWORD }}
          cleanup: true
          passive: true
          local_folder: ./dist/
          remote_folder: dev.metroui.org.ua/
          